const hotels = [
  {
    id: '1',
    name: 'Restaurant Casa Colibrí',
    location: 'a 5 minutos del centro',
    price: 2500,
    image: require('../assets/Colibrí/Coli.jpeg'),
    image1: require('../assets/Colibrí/Coli1.webp'),
    image2: require('../assets/Colibrí/Coli2.jpeg'),
    image3: require('../assets/Colibrí/Coli3.jpeg'),
    details: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat nisl vel pretium lectus quam id leo. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Justo laoreet sit amet cursus sit`,
  },
  {
    id: '2',
    name: 'Restaurant Patio Grande',
    location: '20 minutos del centro',
    price: 2000,
    image: require('../assets/Patio/Patio.webp'),
    image1: require('../assets/Patio/Patio1.webp'),
    image2: require('../assets/Patio/Patio2.jpeg'),
    image3: require('../assets/Patio/Patio3.jpeg'),
    details: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat nisl vel pretium lectus quam id leo. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Justo laoreet sit amet cursus sit`,
  },
  {
    id: '3',
    name: 'Restaurant Casa Pedro',
    location: '5 minutos del centro',
    price: 1500,
    image: require('../assets/Pedro/Pedro.jpeg'),
    image1: require('../assets/Patio/Patio1.webp'),
    image2: require('../assets/Pedro/Pedro2.jpeg'),
    image3: require('../assets/Pedro/Pedro3.jpeg'),
    details: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat nisl vel pretium lectus quam id leo. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Justo laoreet sit amet cursus sit`,
  },
  {
    id: '4',
    name: 'Restaurant Placeres',
    location: '15 min del centro',
    price: 10000,
    image: require('../assets/Placeres/Place.jpeg'),
    image1: require('../assets/Placeres/Place1.jpeg'),
    image2: require('../assets/Placeres/Place2.jpeg'),
    image3: require('../assets/Placeres/Place3.webp'),
    details: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consequat nisl vel pretium lectus quam id leo. Velit euismod in pellentesque massa placerat duis ultricies lacus sed. Justo laoreet sit amet cursus sit`,
  },
];

export default hotels;
